config/routes.rb
Rails.application.routes.draw do
  
 

  resources :states, only: :index
  resources :b2b_ordered_items
  resources :contacts
  resources :b2b_orders
  get 'credit_approval/index'

  resources :product_requests
  resources :addmembers do
    post 'add_to_network', :on => :collection
  end
  resources :supplies
  get 'b2b/index'

  get 'walk_in/index'

  get 'operator/index'

 

  resources :order_histroy
  resources :after_b2b_order
resources :after_order
resources :orders
  resources :walk_in
  resources :packings
  resources :operator
  resources :feedbacks
  resources :credits do
    post 'credit_update', :on => :collection
  end
  resources :privateoffers
  resources :approval
  resources :slabs
  resources :offer_steps
  resources :invites
  get 'gridmarketplace/index'

  resources :notifications
  resources :claim_wastages
  namespace :admin do
    resources :admins
    resources :users
    resources :carts
    resources :chats
    resources :cheps
    resources :customers
    resources :employees
    resources :forklifts
    resources :growers
    resources :marketplaces
    resources :messages
    resources :networks
    resources :offers
  
    resources :ordered_items
    resources :products
    resources :purchases
    resources :reports
    resources :sales
    resources :sellers
    resources :services
    resources :settings
    resources :stocks

    root to: "admins#index"
  end

resources :buyer_steps
  resources :messages
  resources :cheps
  resources :forklifts
  resources :employees
  get '/home', :to => redirect('/index.html')

resources :after_signup
resources :seller_steps
  resources :chats do
    post 'customer_message', :on => :collection
    post 'seller_message', :on => :collection
  end
  resources :ordered_items do
    post 'approve_order', :on => :collection
    post 'walk_in_add_items', :on => :collection
  end 
  resources :settings
  resources :reports
  resources :networks
  resources :services
  resources :sales
  resources :purchases
  resources :marketplaces
  resources :customers
  devise_for :admins
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  resources :offers
  resources :sellers
  resources :stocks
  resources :growers
  resources :products
  resources :dashboard
  resources :gridmarketplace
  resources :cart do
  post 'checkout', :on => :collection
  post 'add_to_cart', :on => :collection
end

  root to: "marketplaces#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :customer
  belongs_to :offer
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :order
  belongs_to :customer
  belongs_to :seller
end

app/models/chep.rb
class Chep < ActiveRecord::Base
  belongs_to :customer
  belongs_to :order
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :order
  belongs_to :employee
end

app/models/grower.rb
class Grower < ActiveRecord::Base
	has_many :supplies, dependent: :delete_all
end

app/models/invite.rb
class Invite < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :chat
end

app/models/network.rb
class Network < ActiveRecord::Base
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :stock
  belongs_to :offer
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :seller
end

app/models/packing.rb
class Packing < ActiveRecord::Base
  belongs_to :employee
  belongs_to :order
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/seller.rb
class Seller < ActiveRecord::Base
	 has_many :offers
	 has_many :products
	 mount_uploader :logo_for_customer_area, ImageUploader
	 mount_uploader :logo_for_invoices, ImageUploader
end

app/models/slab.rb
class Slab < ActiveRecord::Base
  belongs_to :offer
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :product
  belongs_to :grower
  
end

app/models/supply.rb
class Supply < ActiveRecord::Base
mount_uploader :image, ImageUploader
  belongs_to :grower
  belongs_to :employee

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :authy_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
    skip_before_action :verify_authenticity_token
  protect_from_forgery prepend: true, with: :exception
  before_action :authenticate_user!
  before_action :set_seller, only: [:show, :edit, :update, :destroy]

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
         session[:seller_id] = @seller.id
        format.html { redirect_to  seller_steps_path }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        session[:seller_id] = @seller.id
        format.html { redirect_to  seller_steps_path}
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to networks_path, notice: 'Seller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:business_name, :seller_type, :code, :status, :account_type, :business_legal_name, :owner, :market_location, :owner_title, :mobile, :seller_email, :office_phone, :owner_mobile_no, :owner_email, :alternative_contact_name, :alternative_title, :alternative_mobile_number, :fax, :web, :office_address, :shipping_address, :warehouse_address, :billing_address, :logo_for_customer_area, :logo_for_invoices, :approved_by, :member_of_smcs, :smcs_no, :abn_no, :tax_file_no, :other, :certificates, :bank_account_type, :bank_name, :bank_address, :account_name, :account_number, :swift_code, :wire_transfer_code,:uid,:market_drop_off_location,:in_network_of,:credit_limit,:credit_utilized,:credit_available,:credit_due,:credit_type,:Coop_type,:Coop_ref_no,:credit_terms,:coop_credit,:coop_credit_limit,:coop_credit_utilized,:coop_credit_available,:coop_credit_due,:chep_issued,:chep_due,:chep_received,:in_chep_network_of,:pincode,:state,:country,:hometown,:BSB)
    end
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/views/sellers/_form.html.erb
<%= form_for(@seller) do |f| %>
  <% if @seller.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seller.errors.count, "error") %> prohibited this seller from being saved:</h2>

      <ul>
      <% @seller.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="box">
    <div class="box-body">
    <br/>
    <div class="mb-3">
        <div class="mb-3 nav-active-success">
          <ul class="nav nav-pills" data-nav>
            <li class="nav-item active">
              <a class="nav-link" href="#">
                Business Information
              </a>
            </li>
              
            <li class="nav-item">
              <a class="nav-link"  href="#">Addresses</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">
                Business & Bank Information
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                Approval
              </a>
            </li>
          </ul>
        </div>

    <br/>
 
      <form>
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :business_name %>
            <%= f.text_field :business_name, class: "form-control", placeholder: "ABC Pty Ltd" %>
            
          </div>
          <div class="form-group col-md-6">
            <%= f.label :seller_type,'User Type' %> <br/>
             <%= f.select :seller_type, ['Buyers','Wholesalers','Both'],{}, { :class => 'btn white dropdown-toggle' }%>
          </div>
        </div>
        
        <div class="form-row">
        <div class="form-group col-md-6">
          <%= f.label :code %><br>
   <%= f.text_field :code, class: "form-control", placeholder: "ABC112"  %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :status  %><br>
    <%= f.select :status, ['Active','On-Hold'],{}, { :class => 'btn white dropdown-toggle' }%>
        </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :account_type %> <br/>
         <%= f.select :account_type, ['Normal','Premium'],{}, { :class => 'btn white dropdown-toggle' }%>
          </div>

          <div class="form-group col-md-6">
            <%= f.label :business_legal_name %> <br/>
            <%= f.text_field :business_legal_name, class: "form-control", placeholder: "ABC Pty Ltd"  %>
          </div>
          
        </div>
         <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :seller_email %>
            <%= f.text_field :seller_email, class: "form-control", placeholder: "abc@abc.com" %>
            
          </div>
           <div class="form-group col-md-6">
            <%= f.label :mobile,'Seller Mobile'%> <br/>
            <%= f.text_field :mobile, class: "form-control", placeholder:  "0412 123 123" %>
          </div>
          
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :owner, 'Owner Name' %> <br/>
          <%= f.text_field :owner, class: "form-control", placeholder: "John Smith"  %>
          </div>
<div class="form-group col-md-6">
            <%= f.label :owner_title %> <br/>
            <%= f.text_field :owner_title, class: "form-control", placeholder: "Mr/Ms" %>
          </div>
         
          
        </div>
          

         
         <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :owner_mobile_no %>
            <%= f.text_field :owner_mobile_no, class: "form-control", placeholder:  "0412 123 123" %>
            
          </div>
          <div class="form-group col-md-6">
            <%= f.label :owner_email %>
            <%= f.text_field :owner_email, class: "form-control", placeholder: "abc@abc.com"  %>
          </div>
        </div>
       
        <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :alternative_contact_name %>
            <%= f.text_field :alternative_contact_name, class: "form-control", placeholder: "Mr X" %>
            
          </div>
          <div class="form-group col-md-6">
            <%= f.label :alternative_mobile_number %>
            <%= f.text_field :alternative_mobile_number, class: "form-control", placeholder: "0412 123 123" %>
            
          </div>
        </div>
<div class="form-row">
          
<div class="form-group col-md-4">
            <%= f.label :office_phone %>
            <%= f.text_field :office_phone, class: "form-control", placeholder: "(02) 1234 1234" %>
          </div>
         
          <div class="form-group col-md-4">
            <%= f.label :fax  %>
            <%= f.text_field :fax , class: "form-control", placeholder: "0412 123 123"  %>
          </div>
           <div class="form-group col-md-4">
            <%= f.label :web  %>
            <%= f.text_field :web , class: "form-control", placeholder: "www.abc.com" %>
            
          </div>
        </div>

        <div class="form-row">
          
          
        </div>

         <div class="form-row">
          <%= f.hidden_field :in_network_of, value: Seller.where(:uid => current_user.id).first.id %>
           <%= f.hidden_field :in_chep_network_of, value: Seller.where(:uid => current_user.id).first.id %>
         
        </div>
         <%= f.submit 'Continue', :class => 'btn btn-fw success' %>
      </form>
    </div>
  </div>
  
  </div>
<% end %>

app/views/sellers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Business name:</strong>
  <%= @seller.business_name %>
</p>

<p>
  <strong>Seller type:</strong>
  <%= @seller.seller_type %>
</p>

<p>
  <strong>Code:</strong>
  <%= @seller.code %>
</p>

<p>
  <strong>Status:</strong>
  <%= @seller.status %>
</p>

<p>
  <strong>Account type:</strong>
  <%= @seller.account_type %>
</p>

<p>
  <strong>Business legal name:</strong>
  <%= @seller.business_legal_name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @seller.owner %>
</p>

<p>
  <strong>Market location:</strong>
  <%= @seller.market_location %>
</p>

<p>
  <strong>Owner title:</strong>
  <%= @seller.owner_title %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @seller.mobile %>
</p>

<p>
  <strong>Seller email:</strong>
  <%= @seller.seller_email %>
</p>

<p>
  <strong>Office phone:</strong>
  <%= @seller.office_phone %>
</p>

<p>
  <strong>Owner mobile no:</strong>
  <%= @seller.owner_mobile_no %>
</p>

<p>
  <strong>Owner email:</strong>
  <%= @seller.owner_email %>
</p>

<p>
  <strong>Alternative contact name:</strong>
  <%= @seller.alternative_contact_name %>
</p>

<p>
  <strong>Alternative title:</strong>
  <%= @seller.alternative_title %>
</p>

<p>
  <strong>Alternative mobile number:</strong>
  <%= @seller.alternative_mobile_number %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @seller.fax %>
</p>

<p>
  <strong>Web:</strong>
  <%= @seller.web %>
</p>

<p>
  <strong>Office address:</strong>
  <%= @seller.office_address %>
</p>

<p>
  <strong>Shipping address:</strong>
  <%= @seller.shipping_address %>
</p>

<p>
  <strong>Warehouse address:</strong>
  <%= @seller.warehouse_address %>
</p>

<p>
  <strong>Billing address:</strong>
  <%= @seller.billing_address %>
</p>

<p>
  <strong>Logo for customer area:</strong>
  <%= @seller.logo_for_customer_area %>
</p>

<p>
  <strong>Logo for invoices:</strong>
  <%= @seller.logo_for_invoices %>
</p>

<p>
  <strong>Approved by:</strong>
  <%= @seller.approved_by %>
</p>

<p>
  <strong>Member of smcs:</strong>
  <%= @seller.member_of_smcs %>
</p>

<p>
  <strong>Smcs no:</strong>
  <%= @seller.smcs_no %>
</p>

<p>
  <strong>Abn no:</strong>
  <%= @seller.abn_no %>
</p>

<p>
  <strong>Tax file no:</strong>
  <%= @seller.tax_file_no %>
</p>

<p>
  <strong>Other:</strong>
  <%= @seller.other %>
</p>

<p>
  <strong>Certificates:</strong>
  <%= @seller.certificates %>
</p>

<p>
  <strong>Bank account type:</strong>
  <%= @seller.bank_account_type %>
</p>

<p>
  <strong>Bank name:</strong>
  <%= @seller.bank_name %>
</p>

<p>
  <strong>Bank address:</strong>
  <%= @seller.bank_address %>
</p>

<p>
  <strong>Account name:</strong>
  <%= @seller.account_name %>
</p>

<p>
  <strong>Account number:</strong>
  <%= @seller.account_number %>
</p>

<p>
  <strong>Swift code:</strong>
  <%= @seller.swift_code %>
</p>

<p>
  <strong>Wire transfer code:</strong>
  <%= @seller.wire_transfer_code %>
</p>

<%= link_to 'Edit', edit_seller_path(@seller) %> |
<%= link_to 'Back', sellers_path %>