config/routes.rb
Rails.application.routes.draw do
  
 

  resources :states, only: :index
  resources :b2b_ordered_items
  resources :contacts
  resources :b2b_orders
  get 'credit_approval/index'

  resources :product_requests
  resources :addmembers do
    post 'add_to_network', :on => :collection
  end
  resources :supplies
  get 'b2b/index'

  get 'walk_in/index'

  get 'operator/index'

 

  resources :order_histroy
  resources :after_b2b_order
resources :after_order
resources :orders
  resources :walk_in
  resources :packings
  resources :operator
  resources :feedbacks
  resources :credits do
    post 'credit_update', :on => :collection
  end
  resources :privateoffers
  resources :approval
  resources :slabs
  resources :offer_steps
  resources :invites
  get 'gridmarketplace/index'

  resources :notifications
  resources :claim_wastages
  namespace :admin do
    resources :admins
    resources :users
    resources :carts
    resources :chats
    resources :cheps
    resources :customers
    resources :employees
    resources :forklifts
    resources :growers
    resources :marketplaces
    resources :messages
    resources :networks
    resources :offers
  
    resources :ordered_items
    resources :products
    resources :purchases
    resources :reports
    resources :sales
    resources :sellers
    resources :services
    resources :settings
    resources :stocks

    root to: "admins#index"
  end

resources :buyer_steps
  resources :messages
  resources :cheps
  resources :forklifts
  resources :employees
  get '/home', :to => redirect('/index.html')

resources :after_signup
resources :seller_steps
  resources :chats do
    post 'customer_message', :on => :collection
    post 'seller_message', :on => :collection
  end
  resources :ordered_items do
    post 'approve_order', :on => :collection
    post 'walk_in_add_items', :on => :collection
  end 
  resources :settings
  resources :reports
  resources :networks
  resources :services
  resources :sales
  resources :purchases
  resources :marketplaces
  resources :customers
  devise_for :admins
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  resources :offers
  resources :sellers
  resources :stocks
  resources :growers
  resources :products
  resources :dashboard
  resources :gridmarketplace
  resources :cart do
  post 'checkout', :on => :collection
  post 'add_to_cart', :on => :collection
end

  root to: "marketplaces#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :customer
  belongs_to :offer
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :order
  belongs_to :customer
  belongs_to :seller
end

app/models/chep.rb
class Chep < ActiveRecord::Base
  belongs_to :customer
  belongs_to :order
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :order
  belongs_to :employee
end

app/models/grower.rb
class Grower < ActiveRecord::Base
	has_many :supplies, dependent: :delete_all
end

app/models/invite.rb
class Invite < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :chat
end

app/models/network.rb
class Network < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :customer
  belongs_to :seller
  belongs_to :order
  belongs_to :offer
  belongs_to :stock
  belongs_to :product
  belongs_to :chat
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :stock
  belongs_to :offer
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :seller
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/seller.rb
class Seller < ActiveRecord::Base
	 has_many :offers
	 has_many :products
	 mount_uploader :logo_for_customer_area, ImageUploader
	 mount_uploader :logo_for_invoices, ImageUploader
end

app/models/slab.rb
class Slab < ActiveRecord::Base
  belongs_to :offer
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :product
  belongs_to :grower
  
end

app/models/supply.rb
class Supply < ActiveRecord::Base
mount_uploader :image, ImageUploader
  belongs_to :grower
  belongs_to :employee

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :authy_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:customer_id, :seller_id, :order_id, :offer_id, :stock_id, :product_id, :chat_id, :content, :ntype)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.text_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :seller_id %><br>
    <%= f.text_field :seller_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.text_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :offer_id %><br>
    <%= f.text_field :offer_id %>
  </div>
  <div class="field">
    <%= f.label :stock_id %><br>
    <%= f.text_field :stock_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :chat_id %><br>
    <%= f.text_field :chat_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :ntype %><br>
    <%= f.text_field :ntype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Seller</th>
      <th>Order</th>
      <th>Offer</th>
      <th>Stock</th>
      <th>Product</th>
      <th>Chat</th>
      <th>Content</th>
      <th>Ntype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.customer %></td>
        <td><%= notification.seller %></td>
        <td><%= notification.order %></td>
        <td><%= notification.offer %></td>
        <td><%= notification.stock %></td>
        <td><%= notification.product %></td>
        <td><%= notification.chat %></td>
        <td><%= notification.content %></td>
        <td><%= notification.ntype %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @notification.customer %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @notification.seller %>
</p>

<p>
  <strong>Order:</strong>
  <%= @notification.order %>
</p>

<p>
  <strong>Offer:</strong>
  <%= @notification.offer %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @notification.stock %>
</p>

<p>
  <strong>Product:</strong>
  <%= @notification.product %>
</p>

<p>
  <strong>Chat:</strong>
  <%= @notification.chat %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notification.content %>
</p>

<p>
  <strong>Ntype:</strong>
  <%= @notification.ntype %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>