config/routes.rb
Rails.application.routes.draw do
  
 

  resources :states, only: :index
  resources :b2b_ordered_items
  resources :contacts
  resources :b2b_orders
  get 'credit_approval/index'

  resources :product_requests
  resources :addmembers do
    post 'add_to_network', :on => :collection
  end
  resources :supplies
  get 'b2b/index'

  get 'walk_in/index'

  get 'operator/index'

 

  resources :order_histroy
  resources :after_b2b_order
resources :after_order
resources :orders
  resources :walk_in
  resources :packings
  resources :operator
  resources :feedbacks
  resources :credits do
    post 'credit_update', :on => :collection
  end
  resources :privateoffers
  resources :approval
  resources :slabs
  resources :offer_steps
  resources :invites
  get 'gridmarketplace/index'

  resources :notifications
  resources :claim_wastages
  namespace :admin do
    resources :admins
    resources :users
    resources :carts
    resources :chats
    resources :cheps
    resources :customers
    resources :employees
    resources :forklifts
    resources :growers
    resources :marketplaces
    resources :messages
    resources :networks
    resources :offers
  
    resources :ordered_items
    resources :products
    resources :purchases
    resources :reports
    resources :sales
    resources :sellers
    resources :services
    resources :settings
    resources :stocks

    root to: "admins#index"
  end

resources :buyer_steps
  resources :messages
  resources :cheps
  resources :forklifts
  resources :employees
  get '/home', :to => redirect('/index.html')

resources :after_signup
resources :seller_steps
  resources :chats do
    post 'customer_message', :on => :collection
    post 'seller_message', :on => :collection
  end
  resources :ordered_items do
    post 'approve_order', :on => :collection
    post 'walk_in_add_items', :on => :collection
  end 
  resources :settings
  resources :reports
  resources :networks
  resources :services
  resources :sales
  resources :purchases
  resources :marketplaces
  resources :customers
  devise_for :admins
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  resources :offers
  resources :sellers
  resources :stocks
  resources :growers
  resources :products
  resources :dashboard
  resources :gridmarketplace
  resources :cart do
  post 'checkout', :on => :collection
  post 'add_to_cart', :on => :collection
end

  root to: "marketplaces#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :customer
  belongs_to :offer
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :order
  belongs_to :customer
  belongs_to :seller
end

app/models/chep.rb
class Chep < ActiveRecord::Base
  belongs_to :customer
  belongs_to :order
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :order
  belongs_to :employee
end

app/models/grower.rb
class Grower < ActiveRecord::Base
	has_many :supplies, dependent: :delete_all
end

app/models/invite.rb
class Invite < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :chat
end

app/models/network.rb
class Network < ActiveRecord::Base
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :stock
  belongs_to :offer
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :seller
end

app/models/packing.rb
class Packing < ActiveRecord::Base
  belongs_to :employee
  belongs_to :order
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/seller.rb
class Seller < ActiveRecord::Base
	 has_many :offers
	 has_many :products
	 mount_uploader :logo_for_customer_area, ImageUploader
	 mount_uploader :logo_for_invoices, ImageUploader
end

app/models/slab.rb
class Slab < ActiveRecord::Base
  belongs_to :offer
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :product
  belongs_to :grower
  
end

app/models/supply.rb
class Supply < ActiveRecord::Base
mount_uploader :image, ImageUploader
  belongs_to :grower
  belongs_to :employee

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :authy_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  before_action :set_supply, only: [:show, :edit, :update, :destroy]

  # GET /supplies
  # GET /supplies.json
  def index
    @supplies = Supply.where(:seller_id => Seller.where(:uid => current_user.id).first.id)
  end

  # GET /supplies/1
  # GET /supplies/1.json
  def show
  end

  # GET /supplies/new
  def new
    @supply = Supply.new
  end

  # GET /supplies/1/edit
  def edit
  end

  # POST /supplies
  # POST /supplies.json
  def create
    @supply = Supply.new(supply_params)

    respond_to do |format|
      if @supply.save
        format.html { redirect_to supplies_url, notice: 'Supply was successfully created.' }
        format.json { render :show, status: :created, location: @supply }
      else
        format.html { render :new }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplies/1
  # PATCH/PUT /supplies/1.json
  def update
    respond_to do |format|
      if @supply.update(supply_params)
        format.html { redirect_to supplies_url, notice: 'Supply was successfully updated.' }
        format.json { render :show, status: :ok, location: @supply }
      else
        format.html { render :edit }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplies/1
  # DELETE /supplies/1.json
  def destroy
    @supply.destroy
    respond_to do |format|
      format.html { redirect_to supplies_url, notice: 'Supply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supply
      @supply = Supply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supply_params
      params.require(:supply).permit(:grower_id, :consignment_number, :date_received, :ref_no, :value, :paid, :due, :status, :image, :employee_id,:seller_id)
    end
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/supplies/_form.html.erb
<%= form_for(@supply) do |f| %>
<script type="text/javascript" charset="utf-8">


  function  ISQ()
 {

var value = document.getElementById('supply_value').value;
  var paid = document.getElementById('supply_paid').value;
var due = value - paid;
 document.getElementById('supply_due').value = due;  
  }

 </script>
</script>
  <% if @supply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supply.errors.count, "error") %> prohibited this supply from being saved:</h2>

      <ul>
      <% @supply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="box">
    <div class="box-body">
        
     
<div class="form-row">
        <div class="form-group col-md-6">
            <%= f.label :grower_id %><br>
            <%= f.collection_select :grower_id, Grower.all,:id,:name,{}, { :class => 'btn white dropdown-toggle',:readonly => true } %>
          </div>
          <div class="form-group col-md-6">
            <%= f.label :consignment_number%><br>
            <%= f.text_field :consignment_number, class: "form-control", placeholder: "CONS312412"%>
          </div>
          </div>
          <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :date_received  %><br>
            <input type="text" class="btn white dropdown-toggle datetimepicker" style="width: 100%;">
          </div>

          <div class="form-group col-md-6">
            <%= f.label :ref_no  %><br>
             <%= f.text_field :ref_no, class: "form-control", placeholder: "INV123"%>
          </div>
          
        </div>
           <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :value  %><br>
            <%= f.text_field :value, class: "form-control", placeholder: "10000$"%>
          </div>

          <div class="form-group col-md-6">
            <%= f.label :paid %><br>
             <%= f.text_field :paid, class: "form-control", placeholder: "0$",:onchange => "ISQ();"%>
          </div>
          
        </div>
           <div class="form-row">
          <div class="form-group col-md-6">
            <%= f.label :due  %><br>
            <%= f.text_field :due, class: "form-control", placeholder: "0$",:readonly => true %>
          </div>

          <div class="form-group col-md-6">
            <%= f.label :status %><br>
             <%= f.select :status, ['Pending', 'Paid' ],{}, { :class => 'btn white dropdown-toggle',:readonly => true }%>
          </div>
          
        </div>
          <div class="form-row">
         

          <div class="form-group col-md-6">
            <%= f.label :employee_id,'Entered By' %><br>
              <%= f.collection_select :employee_id, Employee.where(:seller_id => Seller.where(:uid => current_user.id).first.id).order(:name),:name,:name,{}, { :class => 'btn white dropdown-toggle' } %>
          </div>
           <div class="form-group col-md-6">
            <%= f.label :image %><br>
             <%= f.file_field :image %>
          </div>
        </div>

       <%= f.hidden_field :seller_id, value: Seller.where(:uid => current_user.id).first.id %>
       
         <%= f.submit 'Submit', :class => 'btn btn-fw success' %>
      </form>
    </div>
  </div>
  <% end %>

  <link rel="stylesheet" type="text/css" href="/css/bootstrap-datetimepicker.css">
<script src="/js/bootstrap-datepicker.min.js"></script>
<script>
  $(".datetimepicker").datetimepicker(); 
</script>

app/views/supplies/edit.html.erb
<h1>Editing Supply</h1>

<%= render 'form' %>

<%= link_to 'Show', @supply %> |
<%= link_to 'Back', supplies_path %>

app/views/supplies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grower:</strong>
  <%= @supply.grower %>
</p>

<p>
  <strong>Consignment number:</strong>
  <%= @supply.consignment_number %>
</p>

<p>
  <strong>Date received:</strong>
  <%= @supply.date_received %>
</p>

<p>
  <strong>Ref no:</strong>
  <%= @supply.ref_no %>
</p>

<p>
  <strong>Value:</strong>
  <%= @supply.value %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @supply.paid %>
</p>

<p>
  <strong>Due:</strong>
  <%= @supply.due %>
</p>

<p>
  <strong>Status:</strong>
  <%= @supply.status %>
</p>

<p>
  <strong>Image:</strong>
  <%= @supply.image %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @supply.employee %>
</p>

<%= link_to 'Edit', edit_supply_path(@supply) %> |
<%= link_to 'Back', supplies_path %>