config/routes.rb
Rails.application.routes.draw do
  
 

  resources :states, only: :index
  resources :b2b_ordered_items
  resources :contacts
  resources :b2b_orders
  get 'credit_approval/index'

  resources :product_requests
  resources :addmembers do
    post 'add_to_network', :on => :collection
  end
  resources :supplies
  get 'b2b/index'

  get 'walk_in/index'

  get 'operator/index'

 

  resources :order_histroy
  resources :after_b2b_order
resources :after_order
resources :orders
  resources :walk_in
  resources :packings
  resources :operator
  resources :feedbacks
  resources :credits do
    post 'credit_update', :on => :collection
  end
  resources :privateoffers
  resources :approval
  resources :slabs
  resources :offer_steps
  resources :invites
  get 'gridmarketplace/index'

  resources :notifications
  resources :claim_wastages
  namespace :admin do
    resources :admins
    resources :users
    resources :carts
    resources :chats
    resources :cheps
    resources :customers
    resources :employees
    resources :forklifts
    resources :growers
    resources :marketplaces
    resources :messages
    resources :networks
    resources :offers
  
    resources :ordered_items
    resources :products
    resources :purchases
    resources :reports
    resources :sales
    resources :sellers
    resources :services
    resources :settings
    resources :stocks

    root to: "admins#index"
  end

resources :buyer_steps
  resources :messages
  resources :cheps
  resources :forklifts
  resources :employees
  get '/home', :to => redirect('/index.html')

resources :after_signup
resources :seller_steps
  resources :chats do
    post 'customer_message', :on => :collection
    post 'seller_message', :on => :collection
  end
  resources :ordered_items do
    post 'approve_order', :on => :collection
    post 'walk_in_add_items', :on => :collection
  end 
  resources :settings
  resources :reports
  resources :networks
  resources :services
  resources :sales
  resources :purchases
  resources :marketplaces
  resources :customers
  devise_for :admins
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  resources :offers
  resources :sellers
  resources :stocks
  resources :growers
  resources :products
  resources :dashboard
  resources :gridmarketplace
  resources :cart do
  post 'checkout', :on => :collection
  post 'add_to_cart', :on => :collection
end

  root to: "marketplaces#index"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :customer
  belongs_to :offer
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :order
  belongs_to :customer
  belongs_to :seller
end

app/models/chep.rb
class Chep < ActiveRecord::Base
  belongs_to :customer
  belongs_to :order
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :order
  belongs_to :employee
end

app/models/grower.rb
class Grower < ActiveRecord::Base
	has_many :supplies, dependent: :delete_all
end

app/models/invite.rb
class Invite < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :chat
end

app/models/network.rb
class Network < ActiveRecord::Base
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :stock
  belongs_to :offer
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :seller
end

app/models/packing.rb
class Packing < ActiveRecord::Base
  belongs_to :employee
  belongs_to :order
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/sale.rb
class Sale < ActiveRecord::Base
end

app/models/seller.rb
class Seller < ActiveRecord::Base
	 has_many :offers
	 has_many :products
	 mount_uploader :logo_for_customer_area, ImageUploader
	 mount_uploader :logo_for_invoices, ImageUploader
end

app/models/slab.rb
class Slab < ActiveRecord::Base
  belongs_to :offer
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :product
  belongs_to :grower
  
end

app/models/supply.rb
class Supply < ActiveRecord::Base
mount_uploader :image, ImageUploader
  belongs_to :grower
  belongs_to :employee

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :authy_authenticatable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
end

app/controllers/slabs_controller.rb
class SlabsController < ApplicationController
  before_action :set_slab, only: [:show, :edit, :update, :destroy]

  # GET /slabs
  # GET /slabs.json
  def index
    @slabs = Slab.all
  end

  # GET /slabs/1
  # GET /slabs/1.json
  def show
  end

  # GET /slabs/new
  def new
    @slab = Slab.new
  end

  # GET /slabs/1/edit
  def edit
  end

  # POST /slabs
  # POST /slabs.json
  def create
    @slab = Slab.new(slab_params)

    respond_to do |format|
      if @slab.save
        format.html { redirect_to @slab, notice: 'Slab was successfully created.' }
        format.json { render :show, status: :created, location: @slab }
      else
        format.html { render :new }
        format.json { render json: @slab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slabs/1
  # PATCH/PUT /slabs/1.json
  def update
    respond_to do |format|
      if @slab.update(slab_params)
        format.html { redirect_to @slab, notice: 'Slab was successfully updated.' }
        format.json { render :show, status: :ok, location: @slab }
      else
        format.html { render :edit }
        format.json { render json: @slab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slabs/1
  # DELETE /slabs/1.json
  def destroy
    @slab.destroy
    respond_to do |format|
      format.html { redirect_to slabs_url, notice: 'Slab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slab
      @slab = Slab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slab_params
      params.require(:slab).permit(:offer_id, :from_quantity, :to_quantity, :value)
    end
end

app/helpers/slabs_helper.rb
module SlabsHelper
end

app/views/slabs/_form.html.erb
<%= form_for(@slab) do |f| %>
  <% if @slab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slab.errors.count, "error") %> prohibited this slab from being saved:</h2>

      <ul>
      <% @slab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :offer_id %><br>
    <%= f.text_field :offer_id %>
  </div>
  <div class="field">
    <%= f.label :from_quantity %><br>
    <%= f.number_field :from_quantity %>
  </div>
  <div class="field">
    <%= f.label :to_quantity %><br>
    <%= f.number_field :to_quantity %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slabs/edit.html.erb
<h1>Editing Slab</h1>

<%= render 'form' %>

<%= link_to 'Show', @slab %> |
<%= link_to 'Back', slabs_path %>

app/views/slabs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Slabs</h1>

<table>
  <thead>
    <tr>
      <th>Offer</th>
      <th>From quantity</th>
      <th>To quantity</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slabs.each do |slab| %>
      <tr>
        <td><%= slab.offer %></td>
        <td><%= slab.from_quantity %></td>
        <td><%= slab.to_quantity %></td>
        <td><%= slab.value %></td>
        <td><%= link_to 'Show', slab %></td>
        <td><%= link_to 'Edit', edit_slab_path(slab) %></td>
        <td><%= link_to 'Destroy', slab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slab', new_slab_path %>

app/views/slabs/new.html.erb
<h1>New Slab</h1>

<%= render 'form' %>

<%= link_to 'Back', slabs_path %>

app/views/slabs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Offer:</strong>
  <%= @slab.offer %>
</p>

<p>
  <strong>From quantity:</strong>
  <%= @slab.from_quantity %>
</p>

<p>
  <strong>To quantity:</strong>
  <%= @slab.to_quantity %>
</p>

<p>
  <strong>Value:</strong>
  <%= @slab.value %>
</p>

<%= link_to 'Edit', edit_slab_path(@slab) %> |
<%= link_to 'Back', slabs_path %>